---

- name: install openproject dependencies
  apt:
    name: '{{item}}'
  with_items:
  - memcached
  - libmysqlclient-dev

- name: clone openproject
  git:
    repo: 'https://github.com/opf/openproject.git'
    dest: '{{openproject_path}}/openproject'
    version: '{{openproject_branch}}/{{openproject_version}}'
    force: yes
    depth: 1
  async: 3600
  poll: 1
  register: cloned_openproject

# do not run this as a handler but as a task here because we will need this before
# end of playbook execution.
- name: change ownership of openproject
  file:
    path: '{{openproject_path}}/openproject'
    owner: '{{openproject_user}}'
    group: '{{openproject_group}}'
    recurse: yes
  when: cloned_openproject.changed

- name: install bundler
  gem:
    name: bundler
    executable: ~{{openproject_user}}/.rbenv/shims/gem
  become: yes
  become_user: '{{openproject_user}}'

- include: plugins.yml

- name: install openproject ruby dependencies
  shell: cd {{openproject_path}}/openproject && ~{{openproject_user}}/.rbenv/shims/bundle install --without postgres sqlite rmagick development test therubyracer
  # FIXME: from ansible v2.0.0 we can use this
  # bundler:
  #   chdir: '{{openproject_path}}/openproject'
  #   executable: ~{{openproject_user}}/.rbenv/shims/bundler
  #   deployment_mode: yes
  #   extra_args: '--without postgres sqlite rmagick development test therubyracer'
  become: yes
  become_user: '{{openproject_user}}'
  async: 3600
  poll: 1
  register: run_bundler
  #  changed_when: '"Installing" in run_bundler.stdout'

- name: install openproject node dependencies
  npm:
    path: '{{openproject_path}}/openproject'
    executable: ~{{openproject_user}}/.nodenv/shims/npm
  become: yes
  become_user: '{{openproject_user}}'
  async: 3600
  poll: 1
