---

- include: user.yml

- include: rbenv.yml
  vars:
    ruby_version: 2.1.6
    rbenv_user: '{{openproject_user}}'
    rbenv_group: '{{openproject_group}}'
  tags: ruby

- include: install.yml
- include: database.yml
  tags: mysql
- include: memcached.yml
- include: configure.yml
- include: unicorn.yml
