---

- include: user.yml

- include: rbenv.yml
  vars:
    ruby_version: 2.1.6
    rbenv_user: '{{openproject_user}}'
    rbenv_group: '{{openproject_group}}'
  tags: ruby

- include: nodenv.yml
  vars:
    node_version: 0.12.7
    nodenv_user: '{{openproject_user}}'
    nodenv_group: '{{openproject_group}}'
  tags: node

- include: install.yml
- include: database.yml
  tags: mysql
- include: memcached.yml
- include: configure.yml
- include: unicorn.yml

- include: nginx.yml
  tags: nginx
