---

- name: install openproject
  template:
    src: openproject.service.jinja2
    dest: /etc/systemd/system/openproject.service
  notify:
  - reload systemd unit files

- name: enable openproject
  service:
    name: openproject
    enabled: yes
    state: started
